services:
  autobidsportal:
    build: .
    environment: &idautobidsenv
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:example@postgres:5432
      SQLALCHEMY_TRACK_MODIFICATIONS: "False"
      REDIS_URL: "redis://redis:6379"
      FLASK_APP: bids_form.py
      AUTOBIDS_SECRET_KEY: secret
      AUTOBIDS_LOG_LEVEL: INFO
      AUTOBIDS_CFMM2TAR_STORAGE_DIR: /home
      AUTOBIDS_TAR2BIDS_DOWNLOAD_DIR: /home
      AUTOBIDS_HEURISTIC_REPO_PATH: /home
      AUTOBIDS_HEURISTIC_DIR_PATH: /home
      AUTOBIDS_MAIL_ENABLED: "False"
    ports: ["5000:5000"]
    depends_on:
      - postgres
      - redis
      - rq
  rq:
    build: .
    command: rq worker
    environment: *idautobidsenv
    depends_on:
      - postgres
      - redis
    restart: on-failure
  redis:
    image: redis:5.0.14
  postgres:
    image: postgres:11
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - "./postgres-db:/var/lib/postgresql/data"
    ports: ["5432:5432"]
