[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79

[tool.djlint]
indent = 2
profile = "jinja"
max_line_length = 79
ignore = "H021"
