# Create a dispatch event to trigger workflows in associated repos
name: Trigger remote repository jobs
on:
  workflow_dispatch:
  push: # Trigger event on new tagged versions
    tags: [v*]

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest release version
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "LATEST_TAG=$(echo ${LATEST_TAG:1})" >> $GITHUB_ENV

      - name: Create dispatch event for autobids-globus
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.BP_PAT_TOKEN }}
          repository: khanlab/autobids-globus
          event-type: autobidsportal_release
          client-payload: '{"version": "${{ env.LATEST_TAG }}"}'
